### ISSUE TITLE
stuck on watching for file changes...

### ISSUE THREAD

**Issue by schro-j** [penrique/GWYF-Maze-builder#3]
HI, I keep getting this error every time after i type the npm start comand. Any ideas?
"[10:13:17 AM] Starting compilation in watch mode...

domain/index.ts:8:15 - error TS2307: Cannot find module './flipgate' or its corresponding type declarations.

8 export * from './flipgate';
                ~~~~~~~~~~~~

domain/index.ts:10:15 - error TS2307: Cannot find module './ghostspinner' or its corresponding type declarations.

10 export * from './ghostspinner';
                 ~~~~~~~~~~~~~~~~

[10:13:20 AM] Found 2 errors. Watching for file changes."

**Comment by pbuhrmann** [comment]
Hey there, I pushed some fixes the other day. See if you can pull those new changes to your repo, it should be all good afterwards :)

**Comment by schro-j** [comment]
Oh great! seems to work very well, Am i missing something on the index.js --help though, I cant seem to change elevation or add multiple holes or anything. the one hole I made looks fantastic though, you did a great job

**Comment by pbuhrmann** [comment]
I've made a couple further adjustments and added some examples that might help you out, just run git pull. And thanks, glad you like it! I remember I had a lot of fun playing around with it at the time, I've also published a bunch of maps on steam too. It works best if you look at the created maps as a template to get started and then add your own things and adjustments on the editor, it saves a lot of time that way.
If you have trouble with anything else just let me know and I'll try to look into it.

**Comment by schro-j** [comment]
works fantastic! only issue im running into isnt on your end but you might know the answer. How do I make 18 holes and stay within that small of a piece count limit?? I mean do you build on hole at a time and merge them somehow?  but seriously fantastic job on the project overall. Going to get a kick out of using it once I figure more of it out

**Comment by pbuhrmann** [comment]
> I mean do you build on hole at a time and merge them somehow?

There's a lot of maps out there that have maybe one small piece of "land" and have you play the same hole over and over but starting from different spots (I love those btw). Thing is that you can have a couple holes or just the one and what really matters is the amount of spawns you create and where you place them so as to create a completely different course even if the ball ends up in the same place. 
So to clarify, you can have one flagpole (or as many as you want) in your map and 18 player spawns, that gets you 18 "holes".

**Comment by schro-j** [comment]
Ahhh i gotcha. Ya I was desperately looking for some other way to build things. Granted I am very novice in 3d software, I just felt like that course editor was awful and was looking for some way of helping out so thank you very much for this. I imagine this was a whole lot of work so I will be sure to put plenty of time  cursing your name as I miss my shots :)

**Comment by schro-j** [comment]
oh and sorry one last question! I saw in the code that there are other types of traps besides the spinner thing. How do I access those?

**Comment by pbuhrmann** [comment]
You mean the names of the traps? I think I got those from inside the editor, placed them and checked their names right there on the screen OR i saved the map and then looked at the saved JSON file inside the custom maps directory.

**Comment by schro-j** [comment]
Oh I just meant the only things I can get to spawn in are the spinner things, the green bombs and the flashing bombs. Is there a way to get stuff from other levels?

**Comment by pbuhrmann** [comment]
The only ones I've added to the project are these:
- flipgate
- fourwingspinner
- ghostspinner
- lightningstrike
- mine
- oildrum
- rock01
- spinningfloor
- walkingturtle
- webspinner

You can find them under ./domain/traps.

However I only added these so they can spawn randomly along with the map you create using the script, you can still place whichever you want using the game's editor. Now, if you want to spawn more types of traps randomly, you can check out **./generator/trapgenerator.ts** and see how it is that they're actually spawned by the script and copy that.

**Comment by schro-j** [comment]
alright thanks, i think I get what you are saying. so looking at the trapgenerator.ts mine says private traps = [FourWingSpinner, FourWingSpinner, Mine, Rock01, OilDrum, OilDrum, OilDrum, OilDrum, OilDrum, OilDrum, OilDrum] 

that would be why those are the only things that are spawning for me?

**Comment by pbuhrmann** [comment]
Yup, exactly. You can modify that or add your own and then just recompile the project with "npm start" and then generate a new map.

**Comment by schro-j** [comment]
youre the man. thanks dude!
